apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-service
  namespace: blazor-service
  labels:
    customer: blazor-customer
    environment: development
    app: blazor-service
spec:
  selector:
    matchLabels:
      app: blazor-service
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blazor-service
    spec:
      containers:
        - image: copterbuddy/blazorservicedev
          name: blazor-service
          imagePullPolicy: Always
          ports:
            - containerPort: 81
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 81
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: blazor-service
                  key: ASPNETCORE_ENVIRONMENT

            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: blazor-service
                  key: Jwt__Issuer

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: blazor-service
                  key: Jwt__Key

            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: blazor-service
                  key: Jwt__Audience

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: blazor-service
                  key: ConnectionStrings__DefaultConnection
---
apiVersion: v1
kind: Service
metadata:
  name: blazor-service
  namespace: blazor-service
  labels:
    app: blazor-service
spec:
  type: ClusterIP
  ports:
    - port: 81
      targetPort: 81
      protocol: TCP
  selector:
    app: blazor-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blazor-ingress
  namespace: blazor-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: localhost:81
      http:
        paths:
        - path: /blazor-service
          pathType: Prefix
          backend:
            service:
              name: blazor-service
              port:
                number: 81
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blazor-service
  namespace: blazor-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blazor-service
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
