apiVersion: v1
data:
  ASPNETCORE_ENVIRONMENT: RGV2ZWxvcG1lbnQK
  Jwt__Issuer: Y29wdGVyYnVkZHkuaG9zdAo=
  Jwt__Key: Y29wdGVyYnVkZHkudXNlcgo=
  Jwt__Audience: Y29wdGVyYnVkZHkudG9rZW4K
  ConnectionStrings__DefaultConnection: U2VydmVyPXRpbnkuZGIuZWxlcGhhbnRzcWwuY29tO1BvcnQ9NTQzMjtEYXRhYmFzZT1lZ3BjZmJzdztVc2VyIElkPWVncGNmYnN3O1Bhc3N3b3JkPVh3Y1NSSXRPNkwzQVAwUE5RanlPSTN6dDZtS0o4c2dyCg==
kind: Secret
metadata:
  name: blazor-service
  namespace: blazor-service
type: Opaque
