apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/copterbuddy/argo-cluster.git
    targetRevision: HEAD
    directory:
      recurse: true
    path: argo-config/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: blazor-service
